# Generated by Django 6.0.1 on 2026-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО (legacy)'),
        ),
    ]
