# Generated by Django 6.0.1 on 2026-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='contracts/')),
                ('signed_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
