# Generated by Django 6.0.1 on 2026-01-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название рекламной кампании')),
                ('channel', models.CharField(max_length=255, verbose_name='Канал продвижения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Бюджет на рекламу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='products.product')),
            ],
        ),
    ]
